### PR TITLE
Use Artifacts and Scratch to manage testdata (enhanced)

### LINKED ISSUE #7: Consider using Artifacts for test data
https://github.com/MagneticParticleImaging/MPIReco.jl/blob/1642d60277b4965010c4c421aa9c7662ac693a8c/test/runtests.jl#L8

Currently every run of PackageEvaluator.jl and likely travis will download the 2.7GB test file from tuhh.de, if you Artifacts PackageEvaluator can cache the data and that will make it also easier for you to cache the data on Travis.

### LINKED ISSUE #12: Tests failing due to ZIP file not being extracted
When I try to run the tests for MPIReco, I get the following error:

> [ Info: download data.zip
> 
> [ Info: extracting data.zip
> ERROR: LoadError: IOError: could not spawn `unzip -oq data.zip`: no such file or directory (ENOENT)
> Stacktrace:
>  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:99
>  [2] #550 at ./process.jl:112 [inlined]
>  [3] setup_stdios(::Base.var"#550#551"{Cmd}, ::Array{Any,1}) at ./process.jl:196
>  [4] _spawn at ./process.jl:111 [inlined]
>  [5] run(::Cmd; wait::Bool) at ./process.jl:439
>  [6] run(::Cmd) at ./process.jl:438
>  [7] top-level scope at /home/schumacherj/.julia/packages/MPIReco/CL5HV/test/runtests.jl:14
>  [8] include(::String) at ./client.jl:439
>  [9] top-level scope at none:6
> in expression starting at /home/schumacherj/.julia/packages/MPIReco/CL5HV/test/runtests.jl:6
> ERROR: Package MPIReco errored during testing

This happens on both Windows and Ubuntu within WSL.
I will try to fix it myself and create a PR, but wanted to mention it here for others wondering about the error aswell (e.g. our HiWi ;)).

### PR DESCRIPTION
**Pull request by jonschumacher**
This PR fixes #12 by using tarballs instead of zip and fixes #7 by merging PR #8 and enhancing it according to a comment in the original code.
It requires a .tar.gz version of the test dataset uploaded to `http://media.tuhh.de/ibi/MPIReco/data.tar.gz`. The matching file for the SHA hashes can be found [here](https://fraunhofer-my.sharepoint.com/:u:/g/personal/jonas_schumacher_imte_fraunhofer_de/ERus0nt7ts1OoxTYHv9y-zMBKrtytJgw8t1W-qxjtDp1WQ?e=CgYLCC).
Please give me a ping after uploading so I can take it offline again.

**Warning:** I only tested this under Windows and Julia 1.6! Due to the use of [Scratch.jl](https://github.com/JuliaPackaging/Scratch.jl), it will only work with Julia 1.5 and above, causing the CI pipeline to fail for earlier versions.

**Note:** Every change of the data.tar.gz-file requires an update of the two hashes in Artifacts.toml. Those hashes can be generated as described [here](https://pkgdocs.julialang.org/v1/artifacts/).

### CODE REVIEW

**Comment by tknopp** [comment]
(close reopen will re-run CI)

**Comment by tknopp** [comment]
This looks really good Jonas! Thank you for tackling this properly.

**Comment by tknopp** [comment]
regarding Julia version, I actually thing the best thing is to just make MPIReco (and all other MPI* packages) depend on Julia 1.6. I can assure you that this will be the case anyway in some months since 1.6 is such a fundamental release (we had the same with 1.3).

Could you work on this PR such that 1.6 gets green? As you said it seems that you need to update the hashed to make CI happy. Once that is done I will merge the PR.

**Comment by jonschumacher** [comment]
Did you recreate the data.tar.gz? The version that I uploaded to the OneDrive was matching the hashes from Artifact.toml. I cleaned out some MacOS-specific files and folders and then packed it. Is that an issue? If so, I will just recreate the hashes for the file that is now at `http://media.tuhh.de/ibi/MPIReco/data.tar.gz`. If you did not recreate it, the data might be corrupted and it doesn't make sense to update the hashes.

**Comment by tknopp** [comment]
yes I recreated it.

**Comment by tknopp** [comment]
So now back at a computer. I missed that you already made the tar file and therefore recreated it this morning. But it seems that CI is still not happy.

**Comment by tknopp** [comment]
you can disable the CI for 1.3 by uncommenting this line https://github.com/MagneticParticleImaging/MPIReco.jl/blob/master/.github/workflows/ci.yml#L18  
on your branch.

**Comment by tknopp** [comment]
and you can also change this line:
   https://github.com/MagneticParticleImaging/MPIReco.jl/blob/master/appveyor.yml#L3
or, alternatively, just remove that file since this is a redundant CI.

**Comment by jonschumacher** [comment]
I was not able to figure out why your file is failing for me, but I uploaded mine to my personal server and CI is happy now. I will change the Julia version in a next commit.

**Comment by tknopp** [comment]
MPIReco currently has an issue with Julia 1.5. The issue has nothing todo with MPIReco itself but with a depending package (or maybe Julia itself). Lets not discuss this issue here and just make you changes work with Julia 1.6.

**Comment by tknopp** [comment]
the Ubuntu issue is real though.

**Comment by jonschumacher** [comment]
Yeah, I see. But I don't get why. CI passed on Ubuntu for commit ad9c433 and I did not change anything apart from the URL. The file cannot be corrupted, since otherwise the hashes would also not work on the other OSes. I am a bit lost at this point. The only thing I can think of at the moment is the unlikely event that the download was corrupted on Ubuntu and therefore failed. I will commit a removal of Appveyor in order to trigger again and see what happens.

**Comment by jonschumacher** [comment]
Alright, CI is happy now even though I don't get why it wasn't in the first place. The logs don't give more info. I guess if this happens more often, we actually have to point our fingers to Artifacts.jl but for now all seems good, right?

**Comment by tknopp** [comment]
not sure why appyevor is still unhappy but lets move forward.

**Pull request merged**
