### PR TITLE
Abstract interface for reconstruction algorithms

### LINKED ISSUE #17: Abstract interface for reconstruction algorithms
As discussed in the slack, the current interface of MPIReco is very focussed on SM-based reconstruction of FFP data. In this issue, I would like to discuss the way to a more general interface that can be used for various reconstruction methods like x-space, SM-based, AI-based approaches for both FFL and FFP systems. As already discussed in Slack, introducing an abstract type `AbstractReconstruction` together with grouping the keyword arguments into structs is probably the best way to go. These might also get some traits attached in order to further group algorithms together and re-use parts that can be shared. What I would see as beneficial is some sort of chaining approach for the steps that are needed to get to the actual reconstruction. This includes e.g. frequency filtering, Radon transform for FFL reconstructions, calling the actual solver and so on. If the whole package would be organized in a chainable way, exchanging parts for trying new stuff could become easier. It could even be possible to create a GUI that can be used to create new algorithms. In order to create this infrastructure, I would like to start a discussion here on what would be needed to get to a new interface and what could be integrated into it.

### PR DESCRIPTION
**Pull request by jonschumacher**
Closes #17

### CODE REVIEW

**Comment by hofmannmartin** [comment]
How would one handle API changes in with this interface? So suppose I create MPIFilesPreprocessingParameters (version x) and then new parameters are added that didn't exist at the time. Am I then bound to version x for Reko or can subsequent versions also handle my old struct?

**Comment by jonschumacher** [comment]
How about adding a function version(::MPIFilesPreprocessingParameters) = v"0.0.1" and the algorithms can check the current version? If the version is wrong, an error is issued and a hint is given to either update the algorithm or use an old commit. MDF files with attached reconstructions should include the commit hashes from MPIReco and MPIFiles in order to make the status of the algorithms traceable. Having new structs with each update might clutter the code too much since one would need dispatch for every single version. Or would you propose adding `AbstractMPIFilesPreprocessingParameters` and then `MPIFilesPreprocessingParametersV1 <: AbstractMPIFilesPreprocessingParameters`?

**Comment by tknopp** [comment]
I think that version issues should be resolved by package versions. If a struct changes, this should change the package version and depending packages need to be updated accordingly.

**Comment by hofmannmartin** [comment]
Is the aim to keep everything backwards compatible as long as possible?

**Comment by tknopp** [comment]
Yes, we should design these structs carefully and then keep them backwards compatible. When things break, we will likely need to update the reconstruction scripts of users. But the user can use a `Project.toml` to be safe.

**Pull request merged**
